name: Stock Data Telegram Alerts

on:
  schedule:
    # Run at 10:00 AM, 1:00 PM, and 5:30 PM IST
    - cron: '30 4 * * *'  # 10:00 AM IST (4:30 UTC)
    - cron: '30 7 * * *'  # 1:00 PM IST (7:30 UTC)
    - cron: '0 12 * * *'  # 5:30 PM IST (12:00 UTC)
    # Check every 15 minutes for updates
    - cron: '*/15 * * * *'
  
  # Trigger when file is updated (assuming using git repository)
  push:
    paths:
      - 'data/processed_data.csv'

jobs:
  analyze_and_notify:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests python-telegram-bot
          
      - name: Process stock data and send alerts
        run: python stock_alerts.py
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
