#
name: Stock Data Telegram Alerts

on:
  schedule:
    - cron: '30 4 * * *'
    - cron: '30 7 * * *'
    - cron: '0 12 * * *'
    - cron: '*/15 * * * *'
  push:
    paths:
      - 'data/processed_data.csv'

jobs:
  analyze_and_notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main  # Explicitly specify the 'main' branch

      - name: List workspace contents (for debugging)
        run: ls -al

      - name: Print content of stock_alerts.py (for debugging)
        run: cat stock_alerts.py

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests python-telegram-bot

      - name: Process stock data and send alerts
        run: python stock_alerts.py
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
